name: PR Verifier

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  verify-pr-title:
    uses: kagenti/.github/.github/workflows/pr-verifier-required.yml@4e535f2436d167295d39d488ce5c44b5a2d49792
